SELECT * FROM CLIENTES;
SELECT * FROM PEDIDOS;
SELECT * FROM LIVROS;

-- Stored procedures
CALL LivroOcupado();

-- Views
SELECT * FROM VER_PEDIDOS;

-- DESCOBRIR PEDIDOS DE UM CLIENTE POR NOME DO CLIENTE
SELECT PED.PEDIDO AS NUMERO_PEDIDO, CLI.NOME AS CLIENTE,
CLI.EMAIL, LI.ID AS CODIGO_LIVRO, LI.NOME AS LIVRO, 
LI.AUTOR, PED.DATAPEDIDO AS DATA_PEDIDO
FROM CLIENTES CLI
INNER JOIN PEDIDOS PED
ON CLI.ID = PED.IDCLIENTE
INNER JOIN LIVROS LI
ON PED.IDLIVRO = LI.ID
WHERE CLI.NOME LIKE "%luiz%";

-- DESCOBRIR PEDIDOS DE UM CLIENTE POR PEDIDO
SELECT CLI.NOME, CLI.EMAIL, LI.NOME, LI.AUTOR,
PED.PEDIDO FROM CLIENTES CLI
INNER JOIN PEDIDOS PED
ON CLI.ID = PED.IDCLIENTE
INNER JOIN LIVROS LI
ON PED.IDLIVRO = LI.ID
WHERE PED.PEDIDO = 1;

INSERT INTO LIVROS(NOME, AUTOR, STATUS) VALUES("", "", 0);
INSERT INTO CLIENTES(NOME, IDADE, EMAIL, DEVEDOR) VALUES("", 20, "", 0);


INSERT INTO PEDIDOS(IDCLIENTE, IDLIVRO) VALUES(2,3);
UPDATE LIVROS SET STATUS = 0 WHERE ID = 2;
UPDATE CLIENTES SET DEVEDOR = 1 WHERE ID = 2;

UPDATE PEDIDOS SET DATAPEDIDO = CURDATE()


